#!/usr/bin/env python3.6

user = { 'admin':True , 'active': True, 'name': 'Kevin' }
string =''

if user['admin'] and user['active']:
	string = "active - admin"
elif user['admin']:
	string = "Admin"
elif user['active']:
	string = "active"

print(string+user['name'])

